config/routes.rb
Rails.application.routes.draw do

  get 'addons/bind'
  get 'addons/cancel'
  get 'addons/order'
  get 'addons/unbind'
  
  get 'subscriptions/cancel'
  get 'subscriptions/change'
  get 'subscriptions/notice'
  get 'subscriptions/order'


  get 'users/assign'
  get 'users/unassign'
  root to: 'visitors#index'
end

app/controllers/addons_controller.rb
class AddonsController < ApplicationController
  before_filter :extract_variables

  def order
  end

  def bind
  end

  def unbind
  end

  def cancel
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def extract_variables
    @accountIdentifier = params[:accountIdentifier] || "dummy-account"
    @accountStatus = params[:accountStatus] || "FREE_TRIAL_EXPIRED"
    @addonBindingId = params[:addonBindingId] || "dummy-addonbinding"
    @addonInstanceId = params[:addonInstanceId] || "dummy-addoninstance"
    @addonOfferingCode = params[:addonOfferingCode] || "type:vendor:plan"
    @editionCode = params[:editionCode] || "BASIC"
    @email = params[:email] || "test-email+creator@appdirect.com"
    @flag = params[:flag] || "STATELESS"
    @noticeType = params[:noticeType] || "DEACTIVATED"
    @openId = params[:openId] || "https://www.appdirect.com/openid/id/ec5d8eda-5cec-444d-9e30-125b6e4b67e2"
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_filter :extract_variables

  def order
  end

  def change
  end

  def cancel
  end

  def notice
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :extract_variables

  def order
  end

  def bind
  end

  def unbind
  end

  def cancel
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/addons/bind.xml.erb
<event>
<creator>
<email><%= @email %></email>
<firstName>DummyCreatorFirst</firstName>
<language>fr</language>
<lastName>DummyCreatorLast</lastName>
<openId>
https://www.appdirect.com/openid/id/ec5d8eda-5cec-444d-9e30-125b6e4b67e2
</openId>
<uuid>ec5d8eda-5cec-444d-9e30-125b6e4b67e2</uuid>
</creator>
<% if @flag != "false" %>
<flag><%= @flag %></flag>
<% end %><marketplace>
<baseUrl>https://acme.appdirect.com</baseUrl>
<partner>ACME</partner>
</marketplace>
<payload>
<account>
<accountIdentifier><%= @accountIdentifier %></accountIdentifier>
<status>ACTIVE</status>
</account>
<addonInstance>
	<id><%= @addonInstanceId %></id>
</addonInstance>
<configuration/>
</payload>
<type>ADDON_BIND</type>
</event>

app/views/addons/cancel.xml.erb
<event>
<creator>
<email><%= @email %></email>
<firstName>DummyCreatorFirst</firstName>
<language>fr</language>
<lastName>DummyCreatorLast</lastName>
<openId>
https://www.appdirect.com/openid/id/ec5d8eda-5cec-444d-9e30-125b6e4b67e2
</openId>
<uuid>ec5d8eda-5cec-444d-9e30-125b6e4b67e2</uuid>
</creator>
<% if @flag != "false" %>
<flag><%= @flag %></flag>
<% end %>
<marketplace>
<baseUrl>https://acme.appdirect.com</baseUrl>
<partner>ACME</partner>
</marketplace>
<payload>
<account>
<accountIdentifier><%= @accountIdentifier %></accountIdentifier>
<status>ACTIVE</status>
</account>
<addonInstance>
	<id><%= @addonInstanceId %></id>
</addonInstance>
<configuration/>
</payload>
<type>ADDON_CANCEL</type>
</event>

app/views/addons/order.xml.erb
<event>
<creator>
<email><%= @email %></email>
<firstName>DummyCreatorFirst</firstName>
<language>fr</language>
<lastName>DummyCreatorLast</lastName>
<openId>
https://www.appdirect.com/openid/id/ec5d8eda-5cec-444d-9e30-125b6e4b67e2
</openId>
<uuid>ec5d8eda-5cec-444d-9e30-125b6e4b67e2</uuid>
</creator>
<% if @flag != "false" %>
<flag><%= @flag %></flag>
<% end %>
<marketplace>
<baseUrl>https://acme.appdirect.com</baseUrl>
<partner>ACME</partner>
</marketplace>
<payload>
<account>
<accountIdentifier><%= @accountIdentifier %></accountIdentifier>
<status>ACTIVE</status>
</account>
<configuration>
<entry>
<key>name</key>
<value>sample-addon</value>
</entry>
</configuration>
<order>
<addonOfferingCode><%= @addonOfferingCode %></addonOfferingCode>
<item>
<quantity>10</quantity>
<unit>UNIT</unit>
</item>
<pricingDuration>MONTHLY</pricingDuration>
</order>
</payload>
<type>ADDON_ORDER</type>
</event>

app/views/addons/unbind.xml.erb
<event>
<creator>
<email><%= @email %></email>
<firstName>DummyCreatorFirst</firstName>
<language>fr</language>
<lastName>DummyCreatorLast</lastName>
<openId>
https://www.appdirect.com/openid/id/ec5d8eda-5cec-444d-9e30-125b6e4b67e2
</openId>
<uuid>ec5d8eda-5cec-444d-9e30-125b6e4b67e2</uuid>
</creator>
<% if @flag != "false" %>
<flag><%= @flag %></flag>
<% end %><marketplace>
<baseUrl>https://acme.appdirect.com</baseUrl>
<partner>ACME</partner>
</marketplace>
<payload>
<account>
<accountIdentifier><%= @accountIdentifier %></accountIdentifier>
<status>ACTIVE</status>
</account>
<addonBinding>
	<id><%= @addonBindingId %></id>
</addonBinding>
<addonInstance>
	<id><%= @addonInstanceId %></id>
</addonInstance>
<configuration/>
</payload>
<type>ADDON_UNBIND</type>
</event>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
      <%= link_to 'GitHub', "https://github.com/timrwilliams/appdirectbin", class: 'navbar-brand' %>

    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "AppDirectBin" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Appdirectbin" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/subscriptions/cancel.xml.erb
<event>
<creator>
<email><%= @email %></email>
<firstName>DummyCreatorFirst</firstName>
<language>fr</language>
<lastName>DummyCreatorLast</lastName>
<openId>
https://www.appdirect.com/openid/id/ec5d8eda-5cec-444d-9e30-125b6e4b67e2
</openId>
<uuid>ec5d8eda-5cec-444d-9e30-125b6e4b67e2</uuid>
</creator>
<% if @flag != "false" %>
	<flag><%= @flag %></flag>
<% end %>
<marketplace>
<baseUrl>https://acme.appdirect.com</baseUrl>
<partner>ACME</partner>
</marketplace>
<payload>
<account>
<accountIdentifier><%= @accountIdentifier %></accountIdentifier>
<status>ACTIVE</status>
</account>
<configuration/>
</payload>
<returnUrl>
https://www.appdirect.com/finishcancel?token=dummyCancel
</returnUrl>
<type>SUBSCRIPTION_CANCEL</type>
</event>

app/views/subscriptions/change.xml.erb
<event>
<creator>
<email><%= @email %></email>
<firstName>DummyCreatorFirst</firstName>
<language>fr</language>
<lastName>DummyCreatorLast</lastName>
<openId>
https://www.appdirect.com/openid/id/ec5d8eda-5cec-444d-9e30-125b6e4b67e2
</openId>
<uuid>ec5d8eda-5cec-444d-9e30-125b6e4b67e2</uuid>
</creator>
<% if @flag != "false" %>
	<flag><%= @flag %></flag>
<% end %>
<marketplace>
<baseUrl>https://acme.appdirect.com</baseUrl>
<partner>ACME</partner>
</marketplace>
<payload>
<account>
<accountIdentifier><%= @accountIdentifier %></accountIdentifier>
<status>ACTIVE</status>
</account>
<configuration/>
<order>
<editionCode><%= @editionCode %></editionCode>
<item>
<quantity>20</quantity>
<unit>USER</unit>
</item>
<item>
<quantity>15</quantity>
<unit>MEGABYTE</unit>
</item>
<pricingDuration>MONTHLY</pricingDuration>
</order>
</payload>
<returnUrl>
https://www.appdirect.com/finishprocure?token=dummyChange
</returnUrl>
<type>SUBSCRIPTION_CHANGE</type>
</event>

app/views/subscriptions/notice.xml.erb
<event>
<% if @flag != "false" %>
	<flag><%= @flag %></flag>
<% end %>
<marketplace>
<baseUrl>https://acme.appdirect.com</baseUrl>
<partner>ACME</partner>
</marketplace>
<payload>
<account>
<accountIdentifier><%= @accountIdentifier %></accountIdentifier>
<status><%= @accountStatus %></status>
</account>
<configuration/>
<notice>
<type><%= @noticeType %></type>
</notice>
</payload>
<type>SUBSCRIPTION_NOTICE</type>
</event>

app/views/subscriptions/order.xml.erb
<event>
<creator>
<email><%= @email %></email>
<firstName>DummyCreatorFirst</firstName>
<language>fr</language>
<lastName>DummyCreatorLast</lastName>
<openId>
https://www.appdirect.com/openid/id/ec5d8eda-5cec-444d-9e30-125b6e4b67e2
</openId>
<uuid>ec5d8eda-5cec-444d-9e30-125b6e4b67e2</uuid>
</creator>
<% if @flag != "false" %>
<flag><%= @flag %></flag>
<% end %>
<marketplace>
<baseUrl>https://acme.appdirect.com</baseUrl>
<partner>ACME</partner>
</marketplace>
<payload>
<company>
<country>CA</country>
<email>company-email@example.com</email>
<name>Example Company Name</name>
<phoneNumber>415-555-1212</phoneNumber>
<uuid>d15bb36e-5fb5-11e0-8c3c-00262d2cda03</uuid>
<website>http://www.example.com</website>
</company>
<configuration>
<entry>
<key>domain</key>
<value>mydomain</value>
</entry>
</configuration>
<order>
<editionCode><%= @editionCode %></editionCode>
<item>
<quantity>10</quantity>
<unit>USER</unit>
</item>
<item>
<quantity>15</quantity>
<unit>MEGABYTE</unit>
</item>
<pricingDuration>MONTHLY</pricingDuration>
</order>
</payload>
<returnUrl>
https://www.appdirect.com/finishprocure?token=dummyOrder
</returnUrl>
<type>SUBSCRIPTION_ORDER</type>
</event>

app/views/users/assign.xml.erb
<event>
    <type>USER_ASSIGNMENT</type>
    <marketplace>
        <baseUrl>https://www.acme-marketplace.com</baseUrl>
        <partner>ACME</partner>
    </marketplace>
    <% if @flag != "false" %>
        <flag><%= @flag %></flag>
    <% end %>
    <creator>
        <email>admin@fakeco</email>
        <firstName>Alice</firstName>
        <lastName>Hacker</lastName>
        <openId>https://www.acme-marketplace.com/openid/id/078e23c3-060f-47b4-b1a3-65c3cb2a283d</openId>
    </creator>
    <payload>
        <account>
            <accountIdentifier><%= @accountIdentifier %></accountIdentifier>
        </account>
        <user>
            <email><%= @email %></email>
            <firstName>Bob</firstName>
            <lastName>Bitdiddle</lastName>
            <openId><%= @openId %></openId>
        </user>
    </payload>
</event>

app/views/users/unassign.xml.erb
<event>
<creator>
<email>test-email+creator@appdirect.com</email>
<firstName>DummyCreatorFirst</firstName>
<language>fr</language>
<lastName>DummyCreatorLast</lastName>
<openId>
https://www.appdirect.com/openid/id/ec5d8eda-5cec-444d-9e30-125b6e4b67e2
</openId>
<uuid>ec5d8eda-5cec-444d-9e30-125b6e4b67e2</uuid>
</creator>
<% if @flag != "false" %>
    <flag><%= @flag %></flag>
<% end %>
<marketplace>
<baseUrl>https://acme.appdirect.com</baseUrl>
<partner>ACME</partner>
</marketplace>
<payload>
<account>
    <accountIdentifier><%= @accountIdentifier %></accountIdentifier>
<status>ACTIVE</status>
</account>
<configuration/>
<user>
 <email><%= @email %></email>
<firstName>Bob</firstName>
<lastName>Bitdiddle</lastName>
<openId><%= @openId %></openId>
<uuid>ec5d8eda-5cec-444d-9e30-125b6e4b67e2</uuid>
</user>
</payload>
<type>USER_UNASSIGNMENT</type>
</event>

app/views/visitors/index.html.erb
<div class="container">
<h1>AppDirectBin</h1>
<p>Provides Sample API responses for the AppDirect Addons and Subscriptions API. Please see <a href="https://github.com/timrwilliams/appdirectbin">GitHub</a> for more details.</p>
<h2>Addons API</h2>
<ol>
<li><%= link_to "ADDON_ORDER", addons_order_path(format: :xml) %></li>
<li><%= link_to "ADDON_BIND", addons_bind_path(format: :xml) %></li>
<li><%= link_to "ADDON_UNBIND", addons_unbind_path(format: :xml) %></li>
<li><%= link_to "ADDON_CANCEL", addons_cancel_path(format: :xml) %></li>
</ol>

<h2>Subscriptions API</h2>
<ol>
<li><%= link_to "SUBSCRIPTION_ORDER",subscriptions_order_path(format: :xml) %></li>
<li><%= link_to "SUBSCRIPTION_CANCEL", subscriptions_cancel_path(format: :xml) %></li>
<li><%= link_to "SUBSCRIPTION_CHANGE",subscriptions_change_path(format: :xml) %></li>
<li><%= link_to "SUBSCRIPTION_NOTICE",subscriptions_notice_path(format: :xml) %></li>
</ol>
</div>